(function () { 
    "use strict";
    var m = "bnat-saudi-national-theme",
        b = "bnat-royal-js",
        S = "bnat-national",
        i = "bnatThemeMode",
        D = [
            "body.bnat-royal-js.bnat-national\x20#room{",
            "background:#dfe3e2!important;",
            "color:#1e2a27!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#room\x20*{",
            "box-sizing:border-box;",
            "scrollbar-width:thin;",
            "scrollbar-color:#0d5f3f\x20#d9dfdd;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#room\x20*::-webkit-scrollbar{",
            "width:7px;",
            "height:7px;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#room\x20*::-webkit-scrollbar-track{",
            "background:#d9dfdd;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#room\x20*::-webkit-scrollbar-thumb{",
            "background:#0d5f3f;",
            "border-radius:20px;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#room{",
            "background:linear-gradient(180deg,#f0f3f2,#e5eae8)!important;",
            "color:#1f2d29!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.bg:not(.mic):not(#muteall){",
            "background:#eef1f0!important;",
            "color:#1f2d29!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.bgg{",
            "background:#e5eae8!important;",
            "color:#1f2d29!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.light{",
            "background:#f3f5f4!important;",
            "color:#1f2d29!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.border,",
            "body.bnat-royal-js.bnat-national\x20.borderg{",
            "border-color:#c8d2ce!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.corner{",
            "border-radius:10px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2,",
            "body.bnat-royal-js.bnat-national\x20#d2bc{",
            "background-color:transparent!important;",
            "padding:7px\x206px\x204px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2bc{",
            "background-image:url(\x22https://i.postimg.cc/jjdMRkvS/saudi-emblem-transparent.png\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center\x2052%!important;",
            "background-size:118px\x20auto!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2>.uzr,",
            "body.bnat-royal-js.bnat-national\x20#d2bc>.uzr{",
            "margin:0\x200\x207px!important;",
            "padding:7px!important;",
            "border:1px\x20solid\x20#d0d8d5!important;",
            "border-radius:13px!important;",
            "background:rgba(255,255,255,.72)!important;",
            "box-shadow:0\x204px\x2013px\x20rgba(25,52,43,.07)!important;",
            "transition:.18s\x20ease!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2>.uzr:hover,",
            "body.bnat-royal-js.bnat-national\x20#d2bc>.uzr:hover{",
            "border-color:rgba(13,95,63,.35)!important;",
            "background:#eef2f0!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.u-pic{",
            "min-width:48px!important;",
            "width:48px!important;",
            "height:48px!important;",
            "border:2px\x20solid\x20rgba(13,95,63,.34)!important;",
            "border-radius:13px!important;",
            "background-color:#dfe6e2!important;",
            "box-shadow:0\x204px\x2012px\x20rgba(24,54,43,.12)!important;",
            "background-size:cover!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.u-topic,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.u-topic{",
            "background:rgba(13,95,63,.065)!important;",
            "border-radius:999px!important;",
            "padding:2px\x207px!important;}",
            "body.bnat-royal-js.bnat-national\x20.u-msg{",
            "color:#35443f!important;",
            "line-height:1.65!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.tago,",
            "body.bnat-royal-js.bnat-national\x20.mini,",
            "body.bnat-royal-js.bnat-national\x20.minix{",
            "color:#70807a!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.pmsgc{",
            "background:#edf7f2!important;",
            "border-color:#bcd9cc!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.ppmsgc{",
            "background:#f0f5f2!important;",
            "border-color:#c8d9d1!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.hmsg{",
            "background:#f7f4e8!important;",
            "border-color:#ded4aa!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.unread{",
            "background:linear-gradient(90deg,rgba(13,95,63,.11),rgba(255,255,255,.72))!important;",
            "box-shadow:inset\x203px\x200\x200\x20#0d5f3f!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.tablebox.footer{",
            "background:#eef2f0!important;",
            "border-top:1px\x20solid\x20#ccd6d2!important;",
            "padding:5px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#tbox,",
            "body.bnat-royal-js.bnat-national\x20.tbox{",
            "color:#20332c!important;",
            "background:#f6f8f7!important;",
            "border:1px\x20solid\x20#c5d2cd!important;",
            "border-radius:11px!important;",
            "padding:7px\x2010px!important;",
            "box-shadow:none!important;",
            "caret-color:#0d5f3f!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#tbox:focus,",
            "body.bnat-royal-js.bnat-national\x20.tbox:focus{",
            "outline:none!important;",
            "border-color:#0d5f3f!important;",
            "box-shadow:0\x200\x200\x203px\x20rgba(13,95,63,.09)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20textarea::placeholder,",
            "body.bnat-royal-js.bnat-national\x20input::placeholder{",
            "color:#88958f!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0{",
            "display:flex!important;",
            "gap:4px!important;",
            "padding:5px!important;",
            "margin:0!important;",
            "width:100%!important;",
            "border-top:1px\x20solid\x20rgba(255,255,255,.22)!important;",
            "background:",
            "linear-gradient(rgba(7,84,52,.91),rgba(5,70,43,.94)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)",
            "center/cover\x20no-repeat!important;",
            "box-shadow:0\x20-7px\x2022px\x20rgba(20,55,42,.16)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae{",
            "float:none!important;",
            "width:auto!important;",
            "max-width:none!important;",
            "flex:1\x201\x2020%!important;",
            "min-height:38px!important;",
            "margin:0!important;",
            "padding:8px\x204px!important;",
            "color:#f5fbf8!important;",
            "border:1px\x20solid\x20rgba(255,255,255,.16)!important;",
            "border-radius:9px!important;",
            "background:rgba(255,255,255,.075)!important;",
            "text-shadow:0\x201px\x202px\x20rgba(0,0,0,.16)!important;",
            "transition:.18s\x20ease!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:hover,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae.bn-active-tab{",
            "color:#06472d!important;",
            "background:#eef3f1!important;",
            "border-color:#f6f8f7!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20#pmb[style*=\x22color:\x20orange\x22],",
            "body.bnat-royal-js.bnat-national\x20#d0\x20#pmb[style*=\x22color:orange\x22],",
            "body.bnat-royal-js.bnat-national\x20#d0\x20#pmb[style*=\x22color:\x20rgb(255,\x20165,\x200)\x22]{",
            "color:#ffad2f!important;",
            "text-shadow:0\x200\x209px\x20rgba(255,173,47,.4)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20#pmb[style*=\x22color:\x20orange\x22]\x20span,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20#pmb[style*=\x22color:orange\x22]\x20span,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20#pmb[style*=\x22color:\x20rgb(255,\x20165,\x200)\x22]\x20span{",
            "color:#ffad2f!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#dpnl{",
            "top:0!important;",
            "right:0!important;",
            "bottom:48px!important;",
            "overflow:hidden!important;",
            "border:1px\x20solid\x20#ff0!important;",
            "border-radius:2px\x202px\x200\x200!important;",
            "background:linear-gradient(160deg,#f5f8f6,#ebf0ee)!important;",
            "box-shadow:0\x2018px\x2046px\x20rgba(27,59,47,.16)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#dpnl>div:first-child{",
            "min-height:42px!important;",
            "padding:6px!important;",
            "border-bottom:1px\x20solid\x20#cbd6d2!important;",
            "background:",
            "linear-gradient(rgba(6,87,53,.91),rgba(6,75,47,.93)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)",
            "center/cover\x20no-repeat!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#dpnl\x20.pnhead{",
            "color:#f6f8f7!important;",
            "background:transparent!important;",
            "border:0!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#users,",
            "body.bnat-royal-js.bnat-national\x20#rooms,",
            "body.bnat-royal-js.bnat-national\x20#wall,",
            "body.bnat-royal-js.bnat-national\x20#settings{",
            "background:rgba(243,246,245,.94)!important;",
            "color:#21332d!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#usearch{",
            "position:static!important;",
            "top:auto!important;",
            "z-index:auto!important;",
            "display:block!important;",
            "float:none!important;",
            "width:calc(100%\x20-\x2012px)!important;",
            "height:38px!important;",
            "margin:6px!important;",
            "border-radius:10px!important;",
            "background:#f1f4f3!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#story-board-seperator{",
            "background-color:#0d5f3f!important;",
            "background-image:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#rooms>.bgg,",
            "body.bnat-royal-js.bnat-national\x20#rooms>.label-primary{",
            "min-height:42px!important;",
            "padding:5px!important;",
            "border-bottom:1px\x20solid\x20#c7d6d0!important;",
            "background:#0d5f3f!important;",
            "color:#f6f8f7!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#rooms\x20.room\x20.u-pic{",
            "min-width:50px!important;",
            "width:50px!important;",
            "height:50px!important;",
            "border:2px\x20solid\x20rgba(13,95,63,.29)!important;",
            "border-radius:13px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings{",
            "padding:7px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20button#delete-video-btn{",
            "width:0px!important;",
            "height:0px!important;",
            "min-width:0!important;",
            "min-height:0!important;",
            "padding:0!important;",
            "margin:0!important;",
            "border:0!important;",
            "overflow:hidden!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings>div{",
            "margin:0\x200\x208px!important;",
            "padding:8px!important;",
            "color:#22352e!important;",
            "border:1px\x20solid\x20#d2ddd8!important;",
            "border-radius:12px!important;",
            "background:rgba(255,255,255,.75)!important;",
            "}",
            "#settings\x20#themeModeSwitch{",
            "display:flex!important;",
            "align-items:center!important;",
            "justify-content:space-between!important;",
            "width:100%!important;",
            "min-height:46px!important;",
            "padding:8px\x2011px!important;",
            "margin:4px\x200\x208px!important;",
            "border-radius:11px!important;",
            "cursor:pointer!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch{",
            "color:#f6f8f7!important;",
            "border:1px\x20solid\x20#0a6a43!important;",
            "background:linear-gradient(135deg,#0d6b45,#075034)!important;",
            "box-shadow:0\x205px\x2014px\x20rgba(13,95,63,.15)!important;",
            "}",
            "#settings\x20#themeModeSwitch\x20.bn-theme-title{",
            "display:flex;",
            "align-items:center;",
            "gap:8px;",
            "font-weight:700;",
            "}",
            "#settings\x20#themeModeSwitch\x20.bn-theme-pill{",
            "min-width:92px;",
            "padding:5px\x209px;",
            "border-radius:999px;",
            "text-align:center;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch\x20.bn-theme-pill{",
            "color:#0a5033!important;",
            "background:#eef3f1!important;",
            "border:1px\x20solid\x20rgba(255,255,255,.4)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20input,",
            "body.bnat-royal-js.bnat-national\x20textarea,",
            "body.bnat-royal-js.bnat-national\x20select,",
            "body.bnat-royal-js.bnat-national\x20.form-control{",
            "color:#21342d!important;",
            "background:#f6f8f7!important;",
            "border:1px\x20solid\x20#c6d3ce!important;",
            "border-radius:9px!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20input:focus,",
            "body.bnat-royal-js.bnat-national\x20textarea:focus,",
            "body.bnat-royal-js.bnat-national\x20select:focus,",
            "body.bnat-royal-js.bnat-national\x20.form-control:focus{",
            "outline:none!important;",
            "border-color:#0d5f3f!important;",
            "box-shadow:0\x200\x200\x203px\x20rgba(13,95,63,.08)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20select\x20option{",
            "background:#f6f8f7!important;",
            "color:#21342d!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn,",
            "body.bnat-royal-js.bnat-national\x20.label{",
            "border-radius:8px!important;",
            "transition:.18s\x20ease!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn:hover{",
            "filter:brightness(1.04);",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn-primary,",
            "body.bnat-royal-js.bnat-national\x20.label-primary,",
            "body.bnat-royal-js.bnat-national\x20.bg-primary{",
            "color:#f6f8f7!important;",
            "border-color:#0b6944!important;",
            "background:linear-gradient(135deg,#0e7048,#075438)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn-success,",
            "body.bnat-royal-js.bnat-national\x20.label-success{",
            "color:#f6f8f7!important;",
            "background:linear-gradient(135deg,#19875d,#0c6846)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn-info,",
            "body.bnat-royal-js.bnat-national\x20.label-info{",
            "color:#f6f8f7!important;",
            "background:linear-gradient(135deg,#2f8064,#1b664e)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn-warning,",
            "body.bnat-royal-js.bnat-national\x20.label-warning{",
            "color:#18382b!important;",
            "background:#e8dfb7!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.btn-danger{",
            "color:#f6f8f7!important;",
            "background:linear-gradient(135deg,#c95656,#a93e45)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.badge{",
            "color:#f6f8f7!important;",
            "background:#0d5f3f!important;",
            "border-radius:999px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic{",
            "height:60px!important;",
            "padding:5px!important;",
            "border-bottom:1px\x20solid\x20#c9d5d0!important;",
            "background:linear-gradient(180deg,#e8eeeb,#dde6e2)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic,",
            "body.bnat-royal-js.bnat-national\x20#muteall{",
            "height:50px!important;",
            "border:1px\x20solid\x20#b9cbc3!important;",
            "border-radius:12px!important;",
            "background-color:#f1f4f3!important;",
            "box-shadow:0\x204px\x2011px\x20rgba(26,58,46,.09)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal{",
            "background:rgba(59,75,68,.30)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal-content{",
            "overflow:hidden!important;",
            "color:#21342d!important;",
            "border:1px\x20solid\x20#b9cec5!important;",
            "border-radius:2px\x202px\x200\x200!important;",
            "background:#eef2f0!important;",
            "box-shadow:0\x2018px\x2048px\x20rgba(31,58,48,.18)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal-header{",
            "min-height:42px!important;",
            "padding:8px\x2010px!important;",
            "color:#f6f8f7!important;",
            "border-bottom:1px\x20solid\x20rgba(255,255,255,.18)!important;",
            "background:linear-gradient(135deg,#0d6844,#075035)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal-header\x20.modal-title{",
            "color:#f6f8f7!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal-body{",
            "color:#21342d!important;",
            "background:transparent!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#upro\x20.modal-content{",
            "width:min(360px,calc(100vw\x20-\x2020px))!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mkr\x20.modal-content{",
            "width:min(340px,calc(100vw\x20-\x2020px))!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mkr\x20.modal-body>.break,",
            "body.bnat-royal-js.bnat-national\x20#rpl\x20.modal-body>.r{",
            "background:#eef3f1!important;",
            "color:#21342d!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#pop>div,",
            "body.bnat-royal-js.bnat-national\x20#cw>div,",
            "body.bnat-royal-js.bnat-national\x20#call,",
            "body.bnat-royal-js.bnat-national\x20#not>div,",
            "body.bnat-royal-js.bnat-national\x20#mnot>div,",
            "body.bnat-royal-js.bnat-national\x20#mmnot>div{",
            "color:#21342d!important;",
            "border:1px\x20solid\x20#b8ccc3!important;",
            "border-radius:2px\x202px\x200\x200!important;",
            "background:#eef2f0!important;",
            "box-shadow:0\x2016px\x2040px\x20rgba(30,59,48,.16)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#pop\x20.head,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.head{",
            "min-height:38px!important;",
            "height:38px!important;",
            "border-bottom:1px\x20solid\x20#cbd7d2!important;",
            "background:#e7efeb!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:\x20#fafafa\x22],",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:#fafafa\x22],",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:\x20rgb(250,\x20250,\x20250)\x22]{",
            "background-color:#f3f5f4!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:#efefef\x22],",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:\x20#efefef\x22]{",
            "background-color:#edf2f0!important;",
            "color:#21342d!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:\x20white\x22],",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22background-color:white\x22]{",
            "background-color:#f6f8f7!important;",
            "color:#21342d!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22border-bottom:\x201px\x20solid\x20lavender\x22],",
            "body.bnat-royal-js.bnat-national\x20[style*=\x22border-bottom:1px\x20solid\x20lavender\x22]{",
            "border-bottom-color:#d7e0dc!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#upro\x20.pro{",
            "background:#eef2f0!important;",
            "border-color:#c6d4cf!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.reply{",
            "margin-top:4px!important;",
            "padding-right:5px!important;",
            "border-right:2px\x20solid\x20rgba(13,95,63,.42)!important;",
            "background:rgba(13,95,63,.035)!important;",
            "border-radius:0\x208px\x208px\x200!important;",
            "}",
            "@media(max-width:680px){",
            "body.bnat-royal-js.bnat-national\x20#dpnl{",
            "top:0!important;",
            "right:0!important;",
            "bottom:45px!important;",
            "border-radius:2px\x202px\x200\x200!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2,",
            "body.bnat-royal-js.bnat-national\x20#d2bc{",
            "padding:5px\x204px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2>.uzr,",
            "body.bnat-royal-js.bnat-national\x20#d2bc>.uzr{",
            "padding:5px!important;",
            "border-radius:11px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0{",
            "gap:3px!important;",
            "padding:4px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae{",
            "min-height:37px!important;",
            "padding:7px\x203px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal-content{",
            "max-width:calc(100vw\x20-\x2016px)!important;",
            "}",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2,",
            "body.bnat-royal-js.bnat-national\x20#d2bc,",
            "body.bnat-royal-js.bnat-national\x20#cw,",
            "body.bnat-royal-js.bnat-national\x20#cw>div,",
            "body.bnat-royal-js.bnat-national\x20#chats{",
            "background-image:url(\x22https://i.postimg.cc/jjdMRkvS/saudi-emblem-transparent.png\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center\x2048%!important;",
            "background-size:112px\x20auto!important;",
            "background-attachment:scroll!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2>.uzr,",
            "body.bnat-royal-js.bnat-national\x20#d2bc>.uzr,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.uzr,",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.uzr{",
            "background-color:rgba(244,247,245,.88)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw,",
            "body.bnat-royal-js.bnat-national\x20#cw>div{",
            "background-size:96px\x20auto!important;",
            "background-position:center\x2055%!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats{",
            "background-color:#e8eeeb!important;",
            "background-position:center\x2060%!important;",
            "background-size:105px\x20auto!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats>div,",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.uzr{",
            "border-color:#cfd9d5!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#users,",
            "body.bnat-royal-js.bnat-national\x20#rooms,",
            "body.bnat-royal-js.bnat-national\x20#wall,",
            "body.bnat-royal-js.bnat-national\x20#settings,",
            "body.bnat-royal-js.bnat-national\x20#chats{",
            "background-color:#e8eeeb!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings>div{",
            "background:#f0f4f2!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20input,",
            "body.bnat-royal-js.bnat-national\x20textarea,",
            "body.bnat-royal-js.bnat-national\x20select,",
            "body.bnat-royal-js.bnat-national\x20.form-control{",
            "background:#f1f4f3!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.modal-content,",
            "body.bnat-royal-js.bnat-national\x20#pop>div,",
            "body.bnat-royal-js.bnat-national\x20#cw>div,",
            "body.bnat-royal-js.bnat-national\x20#call,",
            "body.bnat-royal-js.bnat-national\x20#not>div,",
            "body.bnat-royal-js.bnat-national\x20#mnot>div,",
            "body.bnat-royal-js.bnat-national\x20#mmnot>div{",
            "background-color:#edf2f0!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.ware_poster,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.ware_poster,",
            "body.bnat-royal-js.bnat-national\x20.d2\x20.ware_poster{",
            "position:relative!important;",
            "overflow:hidden!important;",
            "min-height:54px!important;",
            "border:1px\x20solid\x20rgba(255,255,255,.18)!important;",
            "border-radius:13px!important;",
            "background-color:#075c3b!important;",
            "background-image:",
            "linear-gradient(90deg,rgba(4,71,44,.92),rgba(7,101,63,.82)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center!important;",
            "background-size:cover!important;",
            "box-shadow:0\x205px\x2015px\x20rgba(9,70,45,.16)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20.u-msg,",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20.u-topic,",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20.tago,",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20.mini,",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20.minix,",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20span,",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20label{",
            "color:#f0f6f3!important;",
            "text-shadow:0\x201px\x202px\x20rgba(0,0,0,.28)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.ware_poster\x20.u-pic{",
            "border-color:rgba(255,255,255,.38)!important;",
            "background-color:rgba(255,255,255,.12)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.cont{",
            "background:#e7ecea!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.cont>.d2,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2{",
            "background-color:#e6ebe9!important;",
            "background-image:url(\x22https://i.postimg.cc/jjdMRkvS/saudi-emblem-transparent.png\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center\x2048%!important;",
            "background-size:128px\x20auto!important;",
            "background-attachment:scroll!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2>.uzr,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.uzr{",
            "background-color:rgba(239,243,241,.84)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.head,",
            "body.bnat-royal-js.bnat-national\x20#cw>div>.head{",
            "color:#f4f8f6!important;",
            "border-bottom:1px\x20solid\x20rgba(255,255,255,.20)!important;",
            "background-color:#075c3b!important;",
            "background-image:",
            "linear-gradient(90deg,rgba(4,70,43,.87),rgba(7,96,60,.76)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center!important;",
            "background-size:cover!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats>.head,",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.head,",
            "body.bnat-royal-js.bnat-national\x20#chats>.bg:first-child{",
            "color:#f4f8f6!important;",
            "background-color:#075c3b!important;",
            "background-image:",
            "linear-gradient(90deg,rgba(4,70,43,.88),rgba(7,96,60,.75)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center!important;",
            "background-size:cover!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2{",
            "background-color:#e6ebe9!important;",
            "background-image:url(\x22https://i.postimg.cc/jjdMRkvS/saudi-emblem-transparent.png\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center\x2048%!important;",
            "background-size:128px\x20auto!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.light,",
            "body.bnat-royal-js.bnat-national\x20.tablebox.footer{",
            "background-color:#e9eeec!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2>.uzr:not(.ware_poster),",
            "body.bnat-royal-js.bnat-national\x20#d2bc>.uzr:not(.ware_poster),",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2>.uzr:not(.ware_poster){",
            "background-color:rgba(238,242,240,.87)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.bg:not(.mic):not(#muteall){",
            "color:#f3f8f5!important;",
            "background-color:#075c3b!important;",
            "background-image:",
            "linear-gradient(90deg,rgba(4,70,43,.90),rgba(7,101,63,.78)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)!important;",
            "background-position:center!important;",
            "background-size:cover!important;",
            "border-color:rgba(255,255,255,.16)!important;",
            "text-shadow:0\x201px\x202px\x20rgba(0,0,0,.22)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.bg:not(.mic):not(#muteall)\x20.label,",
            "body.bnat-royal-js.bnat-national\x20.bg:not(.mic):not(#muteall)\x20i{",
            "color:#f3f8f5!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.border,",
            "body.bnat-royal-js.bnat-national\x20.borderg{",
            "border:none!important;",
            "border-width:0!important;",
            "border-color:transparent!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic{",
            "background-color:#075c3b!important;",
            "background-image:none!important;",
            "color:#000!important;",
            "border:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic,",
            "body.bnat-royal-js.bnat-national\x20#muteall{",
            "background-color:transparent!important;",
            "color:#000!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20span,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20label,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20i,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.fa{",
            "color:#000!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic{",
            "background-color:#075c3b!important;",
            "background-image:",
            "linear-gradient(90deg,rgba(4,70,43,.90),rgba(7,101,63,.78)),",
            "url(\x22https://chatjawaly.com/sico/zklogEua6M.jpg\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center!important;",
            "background-size:cover!important;",
            "color:#000!important;",
            "border:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic.bg,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic{",
            "background-color:transparent!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center!important;",
            "background-size:contain!important;",
            "color:#000!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20#muteall.bg,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20#muteall{",
            "background-image:none!important;",
            "background-color:mediumseagreen!important;",
            "color:#000!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic\x20.u{",
            "background:rgba(222,222,222,.5)!important;",
            "background-image:none!important;",
            "color:#000!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic\x20span,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic\x20label,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic\x20i,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20#muteall\x20span,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20#muteall\x20i{",
            "color:#000!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic.bg,",
            "body.bnat-royal-js.bnat-national\x20#mic\x20.mic{",
            "background-color:transparent!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center!important;",
            "background-size:cover!important;",
            "color:#000!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#rooms\x20.label,",
            "body.bnat-royal-js.bnat-national\x20#rooms\x20.badge{",
            "color:#fff!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.uhtml\x20.mini.u-msg,",
            "body.bnat-royal-js.bnat-national\x20.uhtml\x20.u-msg.mini,",
            "body.bnat-royal-js.bnat-national\x20.room\x20.mini.u-msg,",
            "body.bnat-royal-js.bnat-national\x20.room\x20.u-msg.mini{",
            "text-shadow:none!important;",
            "opacity:1!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#wall\x20#d2bc\x20.u-topic,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.uzr\x20.u-topic,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.u-topic.dots{",
            "opacity:1!important;}",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.label,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.badge,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.btn{",
            "-webkit-text-fill-color:currentColor!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20label.btn[onclick*=\x22nopm\x22],",
            "body.bnat-royal-js.bnat-national\x20#settings\x20label.btn[onclick*=\x22nonot\x22]{",
            "background-color:#0b6a46!important;",
            "background-image:none!important;",
            "color:#fff!important;",
            "-webkit-text-fill-color:#fff!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae.bn-active-tab,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae.active,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:active,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:focus,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:focus-visible{",
            "background-color:transparent!important;",
            "filter:none!important;",
            "transform:none!important;",
            "box-shadow:none!important;",
            "outline:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.uzr:not(.ware_poster),",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.uzr:not(.ware_poster)\x20.u-msg,",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.uzr:not(.ware_poster)\x20.reply{",
            "background-color:transparent!important;",
            "border:none!important;",
            "box-shadow:none!important;}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.uzr:not(.ware_poster){",
            "border-top:none!important;",
            "border-right:none!important;",
            "border-bottom:none!important;",
            "border-left:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.fitimg.u-pic{",
            "border-radius:50%!important;",
            "overflow:hidden!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.hmsg,",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.uzr.hmsg{",
            "background-color:rgba(184,145,65,.09)!important;",
            "background-image:none!important;",
            "border:1px\x20solid\x20rgba(145,112,48,.18)!important;",
            "border-radius:7px!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.pmsgc,",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.uzr.pmsgc{",
            "background-color:rgba(7,92,59,.075)!important;",
            "background-image:none!important;",
            "border:1px\x20solid\x20rgba(7,92,59,.18)!important;",
            "border-radius:7px!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats\x20[style*=\x22color:\x20orange\x22],",
            "body.bnat-royal-js.bnat-national\x20#chats\x20[style*=\x22color:orange\x22],",
            "body.bnat-royal-js.bnat-national\x20#chats\x20[style*=\x22255,\x20165,\x200\x22],",
            "body.bnat-royal-js.bnat-national\x20#chats\x20[style*=\x22255,165,0\x22]{",
            "color:#087a4d!important;",
            "-webkit-text-fill-color:#087a4d!important;",
            "border:1px\x20solid\x20rgba(8,122,77,.48)!important;",
            "border-radius:7px!important;",
            "box-shadow:0\x200\x200\x202px\x20rgba(8,122,77,.08),0\x202px\x208px\x20rgba(8,122,77,.16)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.uzr.bn-orange-chat{",
            "border:1px\x20solid\x20rgba(8,122,77,.48)!important;",
            "border-radius:7px!important;",
            "box-shadow:0\x200\x200\x202px\x20rgba(8,122,77,.08),0\x202px\x208px\x20rgba(8,122,77,.16)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.unread,",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.cc.unread{",
            "background-color:rgba(20,145,88,.14)!important;",
            "background-image:linear-gradient(90deg,rgba(18,126,77,.16),rgba(31,173,106,.07))!important;",
            "border:1px\x20solid\x20rgba(15,139,82,.72)!important;",
            "border-left:4px\x20solid\x20#0b8f55!important;",
            "border-radius:8px!important;",
            "box-shadow:",
            "0\x200\x200\x202px\x20rgba(13,145,84,.12),",
            "0\x203px\x2011px\x20rgba(8,111,65,.30),",
            "inset\x200\x200\x2010px\x20rgba(30,176,105,.06)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.unread\x20.u-topic,",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.unread\x20.u-msg,",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.unread\x20.mini{",
            "text-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#chats\x20.unread\x20.u-pic{",
            "box-shadow:0\x200\x200\x202px\x20rgba(11,143,85,.58)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.flex-grow-1.break.light{",
            "background-color:#edf2f0!important;",
            "background-image:url(\x22https://i.postimg.cc/jjdMRkvS/saudi-emblem-transparent.png\x22)!important;",
            "background-repeat:no-repeat!important;",
            "background-position:center\x20center!important;",
            "background-size:104px\x20auto!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.uzr,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.u-msg{",
            "background-color:transparent!important;",
            "background-image:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.fitimg.u-pic{",
            "border-radius:100%!important;",
            "overflow:hidden!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.uzr,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.u-msg,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.reply{",
            "background-color:transparent!important;",
            "background-image:none!important;",
            "border:none!important;",
            "border-top:none!important;",
            "border-right:none!important;",
            "border-bottom:none!important;",
            "border-left:none!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.fitimg.u-pic{",
            "border-radius:100%!important;",
            "overflow:hidden!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.uzr,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.u-msg,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.reply{",
            "background-color:transparent!important;",
            "background-image:none!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.fitimg.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.fitimg.u-pic{",
            "height:52px!important;",
            "border-radius:100%!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20.c-flex.bgg.border\x20>\x20.cont\x20>\x20.d2.light\x20.fitimg.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#cw\x20.d2\x20.fitimg.u-pic{",
            "border-radius:100%!important;",
            "margin-top:6px!important;",
            "margin-bottom:6px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae{",
            "transition:box-shadow\x20.18s\x20ease,\x20filter\x20.18s\x20ease!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:hover,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:focus,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:focus-visible,",
            "body.bnat-royal-js.bnat-national\x20#d0\x20.ae:active{",
            "background-color:transparent!important;",
            "background-image:none!important;",
            "box-shadow:",
            "0\x200\x200\x201px\x20rgba(255,255,255,.34),",
            "0\x200\x209px\x20rgba(255,255,255,.32),",
            "inset\x200\x200\x207px\x20rgba(255,255,255,.10)!important;",
            "filter:brightness(1.06)!important;",
            "outline:none!important;",
            "transform:none!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.fitimg.u-pic{",
            "border-radius:100%!important;",
            "margin-top:6px!important;",
            "margin-bottom:6px!important;",
            "overflow:hidden!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#d2\x20.u-pic,",
            "body.bnat-royal-js.bnat-national\x20#d2bc\x20.u-pic{",
            "border-radius:100%!important;",
            "margin-top:6px!important;",
            "margin-bottom:6px!important;",
            "border:none!important;",
            "box-shadow:none!important;",
            "overflow:hidden!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow{",
            "display:flex!important;",
            "align-items:center!important;",
            "justify-content:space-between!important;",
            "gap:12px!important;",
            "direction:rtl!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-copy{",
            "flex:1\x201\x20auto!important;",
            "min-width:0!important;",
            "text-align:right!important;",
            "color:inherit!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-heading{",
            "font-weight:700!important;",
            "font-size:15px!important;",
            "line-height:1.35!important;",
            "color:inherit!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-sub{",
            "margin-top:2px!important;",
            "font-size:12px!important;",
            "line-height:1.35!important;",
            "opacity:.72!important;",
            "color:inherit!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch,",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch{",
            "position:relative!important;",
            "flex:0\x200\x2048px!important;",
            "width:48px!important;",
            "min-width:48px!important;",
            "max-width:48px!important;",
            "height:26px!important;",
            "min-height:26px!important;",
            "padding:0!important;",
            "margin:0!important;",
            "border:1px\x20solid\x20rgba(0,0,0,.12)!important;",
            "border-radius:999px!important;",
            "background:#a8afac!important;",
            "background-image:none!important;",
            "box-shadow:inset\x200\x201px\x202px\x20rgba(0,0,0,.10)!important;",
            "overflow:hidden!important;",
            "cursor:pointer!important;",
            "outline:none!important;",
            "filter:none!important;",
            "transform:none!important;",
            "transition:background-color\x20.22s\x20ease,border-color\x20.22s\x20ease,box-shadow\x20.22s\x20ease!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch\x20.bn-theme-switch-knob{",
            "display:block!important;",
            "position:absolute!important;",
            "top:3px!important;",
            "left:3px!important;",
            "width:18px!important;",
            "height:18px!important;",
            "border-radius:100%!important;",
            "background:#f8faf9!important;",
            "box-shadow:0\x201px\x203px\x20rgba(0,0,0,.24)!important;",
            "transition:left\x20.22s\x20ease,box-shadow\x20.22s\x20ease!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch{",
            "background:#158055!important;",
            "border-color:#126d49!important;",
            "box-shadow:inset\x200\x201px\x202px\x20rgba(0,0,0,.10),0\x200\x200\x202px\x20rgba(21,128,85,.08)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch\x20.bn-theme-switch-knob{",
            "left:25px!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#bnatThemeSettingRow{",
            "color:#22352e!important;",
            "background:rgba(255,255,255,.75)!important;",
            "border:1px\x20solid\x20#d2ddd8!important;",
            "box-shadow:none!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch:hover,",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch:focus,",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch:active{",
            "filter:none!important;",
            "transform:none!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow,",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#bnatThemeSettingRow{",
            "display:flex!important;",
            "align-items:center!important;",
            "justify-content:space-between!important;",
            "gap:14px!important;",
            "direction:rtl!important;",
            "min-height:62px!important;",
            "padding:10px\x2012px!important;",
            "margin:7px\x207px\x209px!important;",
            "border:1px\x20solid\x20rgba(35,72,57,.14)!important;",
            "border-radius:12px!important;",
            "background:rgba(248,251,249,.92)!important;",
            "box-shadow:0\x202px\x208px\x20rgba(21,59,44,.07)!important;",
            "color:#22352e!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-copy{",
            "display:flex!important;",
            "flex-direction:column!important;",
            "justify-content:center!important;",
            "flex:1\x201\x20auto!important;",
            "min-width:0!important;",
            "padding:0\x202px!important;",
            "text-align:right!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-heading{",
            "position:relative!important;",
            "display:inline-block!important;",
            "width:max-content!important;",
            "max-width:100%!important;",
            "margin:0!important;",
            "padding-right:11px!important;",
            "font-size:15px!important;",
            "font-weight:800!important;",
            "line-height:1.35!important;",
            "color:#173f30!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-heading:before{",
            "content:\x22\x22!important;",
            "position:absolute!important;",
            "right:0!important;",
            "top:50%!important;",
            "width:5px!important;",
            "height:5px!important;",
            "margin-top:-2.5px!important;",
            "border-radius:100%!important;",
            "background:#8e9994!important;",
            "box-shadow:0\x200\x200\x203px\x20rgba(142,153,148,.10)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-heading:before{",
            "background:#158055!important;",
            "box-shadow:0\x200\x200\x203px\x20rgba(21,128,85,.12)!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#bnatThemeSettingRow\x20.bn-theme-sub{",
            "margin-top:4px!important;",
            "padding-right:11px!important;",
            "font-size:12px!important;",
            "font-weight:600!important;",
            "line-height:1.35!important;",
            "color:#697670!important;",
            "opacity:1!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch,",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch{",
            "flex:0\x200\x2050px!important;",
            "width:50px!important;",
            "min-width:50px!important;",
            "max-width:50px!important;",
            "height:28px!important;",
            "min-height:28px!important;",
            "margin:0\x202px\x200\x200!important;",
            "border-radius:999px!important;",
            "}",
            "body.bnat-royal-js:not(.bnat-national)\x20#settings\x20#themeModeSwitch{",
            "background:#c6cdca!important;",
            "border-color:#aeb8b4!important;",
            "box-shadow:",
            "inset\x200\x201px\x202px\x20rgba(0,0,0,.10),",
            "0\x201px\x203px\x20rgba(0,0,0,.07)!important;",
            "}",
            "body.bnat-royal-js:not(.bnat-national)\x20#settings\x20#themeModeSwitch\x20.bn-theme-switch-knob{",
            "left:4px!important;",
            "top:3px!important;",
            "width:20px!important;",
            "height:20px!important;",
            "background:#fff!important;",
            "box-shadow:0\x201px\x204px\x20rgba(0,0,0,.22)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch{",
            "background:#158055!important;",
            "border-color:#126d49!important;",
            "box-shadow:",
            "inset\x200\x201px\x202px\x20rgba(0,0,0,.10),",
            "0\x200\x200\x202px\x20rgba(21,128,85,.08),",
            "0\x202px\x206px\x20rgba(21,128,85,.12)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20#settings\x20#themeModeSwitch\x20.bn-theme-switch-knob{",
            "left:26px!important;",
            "top:3px!important;",
            "width:20px!important;",
            "height:20px!important;",
            "}",
            "body.bnat-royal-js\x20#settings\x20#themeModeSwitch:hover{",
            "box-shadow:",
            "inset\x200\x201px\x202px\x20rgba(0,0,0,.10),",
            "0\x200\x200\x203px\x20rgba(255,255,255,.55),",
            "0\x202px\x207px\x20rgba(0,0,0,.10)!important;",
            "}",
            "body.bnat-royal-js.bnat-national\x20a.label.tc.border.cp.btn.label-danger.fl{",
            "color:#000!important;",
            "-webkit-text-fill-color:#000!important;",
            "}"
        ]["join"]("\x0a");
    function o(g, G) {
        if (!g) return;
        ("\x20" + g["className"] + "\x20")["indexOf"]("\x20" + G + "\x20") === -0x1 &&
            (g["className"] += (g["className"] ? "\x20" : "") + G);
    }
    function Y(g, G) {
        if (!g) return;
        var t = new RegExp("\x5cs*" + G + "\x5cb", "g");
        g["className"] = g["className"]["replace"](t, "");
    }
    function n() {
        try {
            if (window["localStorage"]) return localStorage["getItem"](i) || "national";
        } catch (g) {}
        return "national";
    }
    function q(g) {
        try {
            window["localStorage"] && localStorage["setItem"](i, g);
        } catch (G) {}
    }
    function J() {
        return (
            document["body"] &&
            ("\x20" + document["body"]["className"] + "\x20")["indexOf"]("\x20" + S + "\x20") !== -0x1
        );
    }
    function O() {
        return !!document["querySelector"](
            "#u1,#u2,#u3,#tlogins,#loginstat," +
                "input[onclick*=\x22login(\x22],button[onclick*=\x22login(\x22]," +
                "[onclick^=\x22login(\x22],[onclick*=\x22\x20login(\x22]"
        );
    }
    function T() {
        if (!document["body"] || O()) return ![];
        var g = document["getElementById"]("room"),
            G = document["getElementById"]("d0"),
            t = document["getElementById"]("settings"),
            Q = document["getElementById"]("tbox");
        if (!g || !G || !t || !Q) return ![];
        var V = G["getElementsByTagName"]("button");
        if (!V || V["length"] < 0x4) return ![];
        return !![];
    }
    function l(g) {
        document["body"] && (Y(document["body"], S), Y(document["body"], b));
        var G = document["getElementById"](m);
        G && G["parentNode"] && G["parentNode"]["removeChild"](G);
        var t = document["getElementById"]("bnatThemeSettingRow");
        t && t["parentNode"] && t["parentNode"]["removeChild"](t), g && q("original");
    }
    function e(g) {
        if (!document["body"]) return;
        if (!T()) {
            l(![]);
            return;
        }
        var G = document["head"] || document["getElementsByTagName"]("head")[0x0];
        if (!G) return;
        var t = document["getElementById"](m);
        !t &&
            ((t = document["createElement"]("style")),
            (t["type"] = "text/css"),
            (t["id"] = m),
            t["styleSheet"] ? (t["styleSheet"]["cssText"] = D) : t["appendChild"](document["createTextNode"](D)),
            G["appendChild"](t)),
            o(document["body"], b),
            g === "national" ? o(document["body"], S) : Y(document["body"], S),
            q(g),
            f();
    }
    function f() {
        var g = document["getElementById"]("themeModeSwitch");
        if (!g) return;
        var G = J();
        g["setAttribute"]("aria-pressed", G ? "true" : "false"),
            g["setAttribute"]("title", G ? "إيقاف\x20المود\x20الوطني" : "تفعيل\x20المود\x20الوطني");
    }
    function K() {
        if (!T()) return;
        var g = document["getElementById"]("settings");
        if (!g) return;
        var G = document["getElementById"]("themeModeSwitch");
        if (G) {
            f();
            return;
        }
        var t = document["createElement"]("div");
        t["id"] = "bnatThemeSettingRow";
        var Q = document["createElement"]("button");
        (Q["type"] = "button"),
            (Q["id"] = "themeModeSwitch"),
            (Q["className"] = "bn-theme-switch"),
            Q["setAttribute"]("aria-label", "تفعيل\x20أو\x20إيقاف\x20المود\x20الوطني"),
            (Q["innerHTML"] = "<span\x20class=\x22bn-theme-switch-knob\x22></span>");
        var V = document["createElement"]("div");
        (V["className"] = "bn-theme-copy"),
            (V["innerHTML"] =
                "<div\x20class=\x22bn-theme-heading\x22>تفعيل\x20المود\x20الوطني</div><div\x20class=\x22bn-theme-sub\x22>سنوات من المجد وما زلنا نعانق السماء، دام عزك يا وطن</div>"),
            (Q["onclick"] = function () {
                if (!T()) return l(![]), ![];
                return e(J() ? "original" : "national"), ![];
            }),
            t["appendChild"](V),
            t["appendChild"](Q),
            g["firstChild"] ? g["insertBefore"](t, g["firstChild"]) : g["appendChild"](t),
            f();
    }
    function M(g) {
        if (!g || g["nodeType"] !== 0x1) return;
        var G = "\x20" + g["className"] + "\x20";
        if (G["indexOf"]("\x20uzr\x20") === -0x1) return;
        var t = g["innerHTML"],
            Q =
                t["indexOf"]("color:\x20orange") !== -0x1 ||
                t["indexOf"]("color:orange") !== -0x1 ||
                t["indexOf"]("255,\x20165,\x200") !== -0x1 ||
                t["indexOf"]("255,165,0") !== -0x1;
        Q ? o(g, "bn-orange-chat") : Y(g, "bn-orange-chat");
    }
    function L() {
        var g = document["getElementById"]("chats");
        if (!g || g["getAttribute"]("data-bnat-orange-bound") === "1") return;
        g["setAttribute"]("data-bnat-orange-bound", "1");
        if (!window["MutationObserver"]) return;
        var G = new MutationObserver(function (t) {
            for (var Q = 0x0; Q < t["length"]; Q++) {
                var V = t[Q]["addedNodes"];
                for (var U = 0x0; U < V["length"]; U++) {
                    var Z = V[U];
                    if (!Z || Z["nodeType"] !== 0x1) continue;
                    var P = Z;
                    while (P && P !== g && ("\x20" + P["className"] + "\x20")["indexOf"]("\x20uzr\x20") === -0x1) {
                        P = P["parentNode"];
                    }
                    P && P !== g && M(P);
                }
            }
        });
        G["observe"](g, { childList: !![], subtree: !![] });
    }
    function x() {
        var g = document["getElementById"]("d0");
        if (!g || g["getAttribute"]("data-bnat-theme-bound") === "1") return;
        g["setAttribute"]("data-bnat-theme-bound", "1"),
            g["addEventListener"](
                "click",
                function (G) {
                    if (!J()) return;
                    var t = G["target"];
                    while (t && t !== g && t["tagName"] !== "BUTTON") {
                        t = t["parentNode"];
                    }
                    if (!t || t === g) return;
                    var Q = g["getElementsByTagName"]("button");
                    for (var V = 0x0; V < Q["length"]; V++) {
                        Q[V]["className"] = Q[V]["className"]["replace"](/\s*bn-active-tab\b/g, "");
                    }
                    o(t, "bn-active-tab");
                },
                ![]
            );
    }
    function I() {
        if (!T()) return l(![]), ![];
        var g = document["head"] || document["getElementsByTagName"]("head")[0x0],
            G = document["body"];
        if (!g || !G) return ![];
        var t = document["getElementById"](m);
        return (
            !t &&
                ((t = document["createElement"]("style")),
                (t["type"] = "text/css"),
                (t["id"] = m),
                t["styleSheet"] ? (t["styleSheet"]["cssText"] = D) : t["appendChild"](document["createTextNode"](D)),
                g["appendChild"](t)),
            o(G, b),
            e(n()),
            K(),
            x(),
            L(),
            !![]
        );
    }
    var v = null,
        u = null;
    function H() {
        var g = T();
        g ? I() : l(![]), (u = g);
    }
    function w() {
        if (!window["MutationObserver"] || v) return;
        (v = new MutationObserver(function () {
            var g = T();
            if (g !== u) {
                H();
                return;
            }
            if (g) {
                var G = document["body"],
                    t = G && ("\x20" + G["className"] + "\x20")["indexOf"]("\x20" + b + "\x20") !== -0x1,
                    Q = n(),
                    V = Q === "national";
                (!t || (V && !J()) || (!V && J())) && I();
            }
        })),
            v["observe"](document["documentElement"] || document, { childList: !![], subtree: !![] });
    }
    var _volOn = !![];
    function _volApply() {
        var g = document["querySelector"]("#muteall .fa");
        if (!g) return;
        if (_volOn) {
            g["style"]["setProperty"]("color", "#0d5f3f", "important");
            g["style"]["setProperty"]("text-shadow", "0 0 8px rgba(13,95,63,.45)", "important");
        } else {
            g["style"]["setProperty"]("color", "#b0bab6", "important");
            g["style"]["setProperty"]("text-shadow", "none", "important");
        }
    }
    function B() {
        if (document["_bnatVolBound"]) return;
        document["_bnatVolBound"] = !![];
        setTimeout(_volApply, 900);
        document["addEventListener"]("click", function (e) {
            var t = e["target"];
            while (t && t !== document) {
                if (t["id"] === "muteall") {
                    _volOn = !_volOn;
                    _volApply();
                    return;
                }
                t = t["parentNode"];
            }
        }, ![]);
    }
    function s() {
        H(), w();
        B();
    }
    document["readyState"] === "loading" ? document["addEventListener"]("DOMContentLoaded", s, ![]) : s(),
        document["addEventListener"](
            "click",
            function (g) {
                var G = g["target"],
                    t = G;
                while (t && t !== document) {
                    var Q = t["getAttribute"] ? t["getAttribute"]("onclick") || "" : "";
                    if (Q["indexOf"]("logout") !== -0x1) {
                        l(![]);
                        return;
                    }
                    t = t["parentNode"];
                }
                var V = G;
                while (V && V !== document && V["tagName"] !== "BUTTON") {
                    V = V["parentNode"];
                }
                V &&
                    V["getAttribute"] &&
                    V["getAttribute"]("data-target") === "#settings" &&
                    setTimeout(function () {
                        T() && (I(), K());
                    }, 0x3c);
            },
            ![]
        );
})();